// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "20113b2e-e610-4a2b-a937-f62215ba0e21");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575877425);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575927010);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575926890);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575927370);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575927250);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575846347);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575832654);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575927130);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 15405);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575578230);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{66f2a0e6-e427-494f-ad96-50f9f2afab99}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1576058254943");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1576060079943");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575911094299");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575914694299");
user_pref("browser.search.region", "GH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.slowStartup.averageTime", 5553);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1576058247);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575578238039");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "f68b06b359504e7d91bbbf5bc58b6446");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 06 Dec 2019 20:25:03 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1575877425);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"254db26f-18bb-432a-bdbc-8b457dcad20c\",\"fxmonitor@mozilla.org\":\"b760d08a-4e13-42d9-b77a-b5d37a2980a7\",\"screenshots@mozilla.org\":\"f7716074-1464-45f6-9046-8d522e65fa30\",\"webcompat-reporter@mozilla.org\":\"9d0211ab-4817-4555-a1d6-74ff59a38dd2\",\"webcompat@mozilla.org\":\"96cf0063-9c88-444d-a89e-87058f876e36\",\"default-theme@mozilla.org\":\"6ba8ce53-3d08-4f07-90cb-d51b53aaabf7\",\"google@search.mozilla.org\":\"6d1c80f4-d886-4e44-bde1-78f882fad2d1\",\"amazondotcom@search.mozilla.org\":\"0aad7194-0353-4ac7-b918-4340bf7ab4ee\",\"bing@search.mozilla.org\":\"fe51cf6a-7778-4f9f-b04f-ef73095c3f25\",\"ddg@search.mozilla.org\":\"e5cd9354-c2e2-4a59-8802-15b71f6739d1\",\"ebay@search.mozilla.org\":\"bf1acc0d-f138-425d-9c09-c2c5f5562970\",\"twitter@search.mozilla.org\":\"ed95c36d-bc90-4c76-bf00-67376feac756\",\"wikipedia@search.mozilla.org\":\"1dedd740-b46c-450d-b61c-d2ea3b2056d8\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1575927529);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575578362);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1575832423);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575578501);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c4f3cc83-505b-4e10-8784-6905f5aa20c9");
user_pref("security.sandbox.plugin.tempDirSuffix", "f8a4a9de-a589-4865-a31b-5e32840c2dbc");
user_pref("services.blocklist.pinning.checked", 1576058381);
user_pref("services.settings.clock_skew_seconds", -130);
user_pref("services.settings.last_etag", "\"1576032042722\"");
user_pref("services.settings.last_update_seconds", 1576058381);
user_pref("services.settings.main.cfr-fxa.last_check", 1576058381);
user_pref("services.settings.main.cfr.last_check", 1576058381);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1576058381);
user_pref("services.settings.main.hijack-blocklists.last_check", 1576058381);
user_pref("services.settings.main.language-dictionaries.last_check", 1576058381);
user_pref("services.settings.main.normandy-recipes.last_check", 1576058381);
user_pref("services.settings.main.sites-classification.last_check", 1576058381);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1576058381);
user_pref("services.settings.security.onecrl.checked", 1576058381);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1575578501);
user_pref("toolkit.startup.last_success", 1576058240);
user_pref("toolkit.telemetry.cachedClientID", "f971281e-c730-4cbf-a88e-a93c318d6d3f");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
